### ISSUE TITLE
BLENDER 3.0.0             Interactive input areas are not shown in the tab. 

### ISSUE THREAD

**Issue by Idol11112222** [ProtoxiDe22/Blender-csv-fcurve-importer#2] opened 2022-08-23 18:43 UTC
I tried to use this add-on for version 3.0, but there are no input fields, can you please update the script for the new version? I'm begging! I really need this script! I didn't find anything else that could move the object using a .csv file!
please...
![Check it, please](https://user-images.githubusercontent.com/105334854/186238216-e5f4cf00-6590-487e-8007-9c3354f38e03.png)

**Comment by ProtoxiDe22** [comment] 2022-08-23 18:55
Duplicate of #1

**Closed as not planned by ProtoxiDe22** 2022-08-23 18:55 UTC
